// This file is autogenerated. Changes will be overwritten.
#include "EWIEGA46WW/moc_camera.cpp"
#include "EWIEGA46WW/moc_fontrenderer.cpp"
#include "EWIEGA46WW/moc_textsimulation.cpp"
#include "EWIEGA46WW/moc_worker.cpp"
